version: '3.8'

services:
  mysqldb:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  backend:
    depends_on:
      - mysqldb
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - app-network

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
