version: '3.9'

services:

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE

  backend:
    restart: always
    env_file: .env
    depends_on:
      - db
    build:
      context: ./backend
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app
    environment:
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - DATABASE_URL=$DATABASE_URL

  frontend:
    image: vite_app
    restart: always
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT

