version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cedb


  backend:
    build: .
    depends_on:
      - db
    ports:
      - '8888:8888'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/cedb
      - NODE_DOCKER_PORT=8888

